{{- if not .Values.postgres.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-test.fullname" . }}
  labels:
    {{- include "postgres-test.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.postgres.credentials.host | quote }}
  DB_PORT: {{ .Values.postgres.credentials.port | quote }}
  DB_NAME: {{ .Values.postgres.credentials.database | quote }}
  DB_USER: {{ .Values.postgres.credentials.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
{{- end }}